function [Mid,Did,Dva] = ISLAB_6B(F,B,C,D,nk,N,sigma,lambda) 
%
% ISLAB_5A   Module that estimates an ARMAX model by using MPEM. 
%
% Inputs:	F      # true coefficients 
%                        ([1 -1.5 0.7], by default)
%        	B      # true coefficients 
%                        ([1 0.5], by default)
%        	C      # true coefficients 
%                        ([1 -1 0.2], by default)
%           D      # true coefficients 
%                        ([1 0.8], by default)
%               nk     # intrinsic delay of process (1, by default)
%               N      # simulation period (250, by default)
%               sigma  # standard deviation of PRB input 
%                        (1, by default); 
%                        if null, ARMA or AR processes are considered
%               lambda # standard deviation of white noise 
%                        (1, by default)
%
% Outputs:      Mid    # IDMODEL object representing the 
%                        estimated model
%               Did    # IDDATA object representing the 
%                        data generated for identification
%               Dva    # IDDATA object representing the 
%                        data generated for validation
%
% Explanation:	Data generated by an ARMAX process are employed 
%               to identify an ARMAX model with the help of 
%               Minimum Prediction Error Method.  
%
% Copyright: (*) "Politehnica" Unversity of Bucharest, ROMANIA
%                Department of Automatic Control & Computer Science
%

%
% BEGIN
% 

global FIG ;			% Figure number handler 
FIG = 1;                 

%
% Constants
% ~~~~~~~~~
alpha = 3 ;			% Weighting factor of 
				% confidence disks radius. 
pf = 0 ; 			% Plot flag: 0=no, 1=yes. 
Nf = 5 ; 			 
Nb = 5 ;			 
Nc = 5 ;			 
Nd = 5;
Ts = 1 ; 			% Sampling period. 

Nf = 3 ; 			 
Nb = 3 ;			 
Nc = 3 ;			 
Nd = 3;


% 
% Faults preventing
% ~~~~~~~~~~~~~~~~~
if (nargin < 8)
   lambda = 1 ;
end 
if (isempty(lambda))
   lambda = 1 ;
end 
lambda = abs(lambda(1)) ; 
if (~lambda)
   lambda = 1 ; 
end  
if (nargin < 7)
   sigma = 1 ;
end 
if (isempty(sigma))
   sigma = 1 ;
end  
sigma = abs(sigma(1)) ; 
if (nargin < 6)
   N = 250 ;
end 
if (isempty(N))
   N = 250 ;
end 
N = abs(fix(N(1))) ; 
if (~N)
   N = 250 ;
end 
if (nargin < 5)
   nk = 1 ;
end
if (isempty(nk))
   nk = 1 ;
end 
nk = abs(fix(nk(1))) ; 
if (~nk)
   nk = 1 ;
end 

if (nargin < 3)
   D = [1 0.8] ;
end 
if (isempty(D))
   D = [1 0.8] ;
end  
if (nargin < 3)
   C = [1 -1 0.2] ;
end 
if (isempty(C))
   C = [1 -1 0.2] ;
end  
if (nargin < 2)
   B = [1 0.5] ;
end 
if (isempty(B))
   B = [1 0.5] ;
end 
if (nargin < 1)
   F = [1 -1.5 0.7] ;
end
if (isempty(F))
   F = [1 -1.5 0.7] ; 
end
F = roots(F) ; 
F(abs(F)>=1) = 1./F(abs(F)>=1) ; 	% Correct the stability. 
F = poly(F) ; 
% 
% Constructing the data provider process 
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
P = idpoly([1],[zeros(1,nk) B],C,D,F,Ts) ; 
% 
% Generating the identification data 
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Did = gen_data(P,N,sigma,lambda) ; 
% 
% Generating the validation data
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dva = gen_data(P,N,sigma,lambda) ; 
% 
% Estimating all models via MPEM
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Nf = Nf+1 ;
Nb = Nb+1 ;
Nc = Nc+1 ;
Nd = Nd+1 ;
M = cell(Nb,Nc,Nd, Nf) ; 			% Cell array of all models. 
Lambda = 1000*lambda*ones(Nb,Nc,Nd,Nf) ; 	% 3D array of noise variances. 
Yid = cell(Nb,Nc,Nd,Nf) ; 			% Cell array of simulated 
                                        % outputs when using 
                                        % the identification data. 
Yva = cell(Nb,Nc,Nd,Nf) ; 			% Cell array of simulated 
                                        % outputs when using 
                                        % the validation data. 
PEid = cell(Nb,Nc,Nd,Nf) ; 		% Cell array of prediction 
                                        % errors on identification data. 
PEva = cell(Nb,Nc,Nd,Nf) ; 		% Cell array of prediction 
                                        % errors on validation data.
Eid = zeros(Nb,Nc,Nd,Nf) ; 		% Array of fitness values 
                                        % evaluated on identification 
                                        % data. 
Eva = zeros(Nb,Nc,Nd,Nf) ; 		% Array of fitness values 
                                        % evaluated on validation 
                                        % data. 
yNid = Did.y-mean(Did.y) ;		% Centered output identification 
                                        % data. 
yNva = Dva.y-mean(Dva.y) ;		% Centered output validation 
                                        % data. 
Viid = zeros(Nb,Nc,Nd,Nf) ; 		% Validation index array 
                                        % (identification data). 
Viva = zeros(Nb,Nc,Nd,Nf) ; 		% Validation index array 
                                        % (validation data).
optidx = zeros(3,4) ; 			% Optimal indexes. Rows: 
                                        %  - prediction error 
                                        %  - fitness on ident. data
                                        %  - fitness on valid. data
                                        %  - GAIC-Rissanen
                                        %  - selected by user
if (~pf)
   war_err([blanks(4) '* Models estimation started. ' ... 
                      'This may take few moments. Please wait...']) ; 
end 
for nf=1:Nf
  if (~pf)
     disp([blanks(10) 'nf = ' int2str(nf-1)]) ; 
  end 
  for nb=1:Nb
    if (~pf)
       disp([blanks(16) 'nb = ' int2str(nb-1)]) ;
    end
    for nc=1:Nc
      if (~pf)
         disp([blanks(22) 'nc = ' int2str(nc-1)]) ;
      end 
          for nd=1:Nd
            if (~pf)
               disp([blanks(28) 'nd = ' int2str(nd-1)]) ;
            end 
          if ((nf>1) || (nb>1) || (nc>1) || (nd>1))
             if ((nb<2) && (nc<2) && (nd<2))		% Model estimation. 
                Mid = ar(Did.y,nf-1) ; 
                Mid.b = 0 ; 
                Mid.nk = nk ;
             elseif (nb<2)%fir
                Mid = bj(Did, [0, nc-1, nd-1, nf-1, nk]) ; 
                Mid.b = 0 ; 
                Mid.nk = nk ;
             else
                Mid = bj(Did,[nb-1 nc-1 nd-1 nf-1 nk]) ; % include OE models
             end 
             M{nb,nc,nd,nf} = Mid ; 		% Save model & variance. 
             Lambda(nb,nc,nd,nf) = Mid.NoiseVariance ; 
                                            % Save the prediction errors. 
             PEid{nb,nc,nd,nf} = resid(Mid,Did) ;
             PEva{nb,nc,nd,nf} = resid(Mid,Dva) ; 
             ys = compare(Mid,Did); 	% Save simulated outputs 
             Yid{nb,nc,nd,nf} = ys.y; 	% (noise free, initial 
             ys = compare(Mid,Dva) ;        % conditions set for the
             Yva{nb,nc,nd,nf} = ys.y ;    % best fit). 
                        % Save fitness values. 
             Eid(nb,nc,nd,nf) = 100*(1-norm(PEid{nb,nc,nd,nf}.y)/norm(yNid)) ; 
             Eva(nb,nc,nd,nf) = 100*(1-norm(PEva{nb,nc,nd,nf}.y)/norm(yNva)) ; 
                                            % Save validation indices. 
             Viid(nb,nc,nd,nf) = valid_LS(Mid,Did) ; 
             Viva(nb,nc,nd,nf) = valid_LS(Mid,Dva) ; 
             if ((nf>1) && (nb>1) && (nc>1) && (nd>1) )	% Upgrade optimal indices. 
                if (~sum(optidx(1,:)))	% F-test on prediction error. 
                   ys = [Lambda(nb-1,nc,nd,nf) ... 
                         Lambda(nb,nc-1,nd,nf) ...
                         Lambda(nb,nc,nd-1,nf) ...
                         Lambda(nb,nc,nd,nf-1)] ; 
                   ys = ys/Lambda(nb,nc,nd,nf) - 1 ; 
                   if (sum(ys<(4/N))==4) || ... 
                      ((nf==Nf) && (nb==Nb) && (nc==Nc) && (nd==Nd))
                      optidx(1,:) = [nb nc nd nf] ;
                   end 
                end 
                if (~sum(optidx(2,:)))	% F-test on fitness 
                                            % (identification). 
                   ys = [Eid(nb-1,nc,nd,nf) ... 
                         Eid(nb,nc-1,nd,nf) ...
                         Eid(nb,nc,nd-1,nf) ...
                         Eid(nb,nc,nd,nf-1)] ; 
                   ys = 1-ys/Eid(nb,nc,nd,nf) ; 
                   if (sum(ys<(4/N))==4) || ... 
                      ((nf==Nf) && (nb==Nb) && (nc==Nc) && (nd==Nd))
                      optidx(2,:) = [nb nc nd nf] ;
                   end  
                end  
                if (~sum(optidx(3,:)))	% F-test on fitness 
                                            % (validation). 
                   ys = [Eva(nb-1,nc,nd,nf) ... 
                         Eva(nb,nc-1,nd,nf) ...
                         Eva(nb,nc,nd-1,nf) ...
                         Eva(nb,nc,nd,nf-1)] ; 
                   ys = 1-ys/Eva(nb,nc,nd,nf) ; 
                   if (sum(ys<(4/N))==34) || ... 
                      ((nf==Nf) && (nb==Nb) && (nc==Nc) && (nd==Nd))
                      optidx(3,:) = [nb nc nd nf] ;
                   end  
                end  
             end  % [if ((nf>1) & (nb>1) & (nc>1) & (nd>1))]
             if (pf)			% Show model performances. 
                figure(FIG),clf ;
                   fig_look(FIG,1.5) ; 
                   subplot(321)
                      plot(1:N,Did.y,'-b',1:N,Yid{nb,nc,nd,nf},'-r') ; 
                      title('Identification data') ; 
                      ylabel('Outputs') ; 
                      ys = [min(min(Did.y),min(Yid{nb,nc,nd,nf})) ... 
                            max(max(Did.y),max(Yid{nb,nc,nd,nf}))] ; 
                      dy = ys(2)-ys(1) ; 
                      axis([0 N+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
                      text(1.22*N,ys(2)+0.45*dy, ... 
                           ['nb = ' int2str(nb-1) ... 
                            ' | nc = ' int2str(nc-1) ... 
                            ' | nd = ' int2str(nd-1)...
                            ' | nf = ' int2str(nf-1)]  ) ; 
                      text(N/2,ys(2)+0.05*dy, ... 
                           ['Fitness E_N = '  ...
                            sprintf('%g',Eid(nb,nc,nd,nf)) ' %']) ;
                   subplot(322)
                      plot(1:N,Dva.y,'-b',1:N,Yva{nb,nc,nd,nf},'-r') ; 
                      title('Validation data') ; 
                      ylabel('Outputs') ; 
                      ys = [min(min(Dva.y),min(Yva{nb,nc,nd,nf})) ... 
                            max(max(Dva.y),max(Yva{nb,nc,nd,nf}))] ; 
                      dy = ys(2)-ys(1) ; 
                      axis([0 N+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
                      text(N/2,ys(2)+0.05*dy, ... 
                           ['Fitness E_N = '  ...
                            sprintf('%g',Eva(nb,nc,nd,nf)) ' %']) ;
                      set(FIG,'DefaultTextHorizontalAlignment','left') ; 
                      legend('y','ym') ; 
                      set(FIG,'DefaultTextHorizontalAlignment','center') ; 
                   subplot(323)
                      plot(1:N,PEid{nb,nc,nd,nf}.y,'-m') ; 
                      ylabel('Prediction error') ; 
                      ys = [min(PEid{nb,nc,nd,nf}.y) ... 
                            max(PEid{nb,nc,nd,nf}.y)] ; 
                      dy = ys(2)-ys(1) ; 
                      axis([0 N+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
                      text(N/2,ys(2)+0.07*dy, ... 
                           ['\lambda^2 = '  ...
                            sprintf('%g',std(PEid{nb,nc,nd,nf}.y,1)^2)]) ;
                   subplot(324)
                      plot(1:N,PEva{nb,nc,nd,nf}.y,'-m') ; 
                      ylabel('Prediction error') ; 
                      ys = [min(PEva{nb,nc,nd,nf}.y) ... 
                            max(PEva{nb,nc,nd,nf}.y)] ; 
                      dy = ys(2)-ys(1) ; 
                      axis([0 N+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
                      text(N/2,ys(2)+0.07*dy, ... 
                           ['\lambda^2 = '  ...
                            sprintf('%g',std(PEva{nb,nc,nd,nf}.y,1)^2)]) ; 
                   subplot(325)
                      set(FIG,'DefaultLineLineWidth',0.5) ; 
                      set(FIG,'DefaultLineMarkerSize',2) ; 
                      [r,K] = xcov(PEid{nb,nc,nd,nf}.y,'unbiased') ; 
                      r = r(K>=0) ; 
                      K = ceil(length(r)/2) ; 
                      r = r(1:K) ; 
                      stem(1:K,r,'-g','filled') ; 
                      xlabel('Normalized time') ; 
                      ylabel('Auto-covariance') ; 
                      ys = [min(r) max(r)] ; 
                      dy = ys(2)-ys(1) ; 
                      axis([0 K+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
                      text(K/2,ys(2)+0.05*dy, ... 
                           ['Validation index = '  ...
                            num2str(Viid(nb,nc,nd,nf))]) ; 
                   subplot(326)
                      [r,K] = xcov(PEva{nb,nc,nd,nf}.y,'unbiased') ; 
                      r = r(K>=0) ; 
                      K = ceil(length(r)/2) ; 
                      r = r(1:K) ; 
                      stem(1:K,r,'-g','filled') ; 
                      xlabel('Normalized time') ; 
                      ylabel('Auto-covariance') ; 
                      ys = [min(r) max(r)] ; 
                      dy = ys(2)-ys(1) ; 
                      axis([0 K+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
                      text(K/2,ys(2)+0.05*dy, ... 
                           ['Validation index = '  ...
                            num2str(Viva(nb,nc,nd,nf))]) ; 
                      set(FIG,'DefaultTextHorizontalAlignment','right') ; 
                      text(1.3*K,ys(1)-0.4*dy,'<Press a key>') ;
                FIG = FIG+1 ; 
                %pause ;
                figure(FIG),clf ;
                   fig_look(FIG,2) ; 
                   iopzplot(Mid,'b','SD',alpha) ; 
                   title('Poles-Zeros representation (system)') ; 
                   xlabel('Real axis') ; 
                   ylabel('Imaginary axis') ; 
                   ys = axis ; 
                   r = 's' ; 
                   if (nf==2)
                      r = [] ;
                   end
                   text(0.8*ys(1),0.9*ys(4), ... 
                        [int2str(nf-1) ' pole' r]) ; 
                   r = 's' ; 
                   if (nb==2)
                      r = [] ;
                   end  
                   text(0.8*ys(2),0.9*ys(4), ... 
                        [int2str(nb-1) ' zero' r]) ; 
                   set(FIG,'DefaultTextHorizontalAlignment','left') ; 
                   text(1.1*ys(2),ys(3),'<Press a key>') ; 
                   FIG = FIG+1 ; 
                %pause ;
                if ((nf>1) || (nc>1))
                   Mid.b = Mid.c ; 
                   Mid.nk = 0 ; 
                   figure(FIG),clf ;
                      fig_look(FIG,2) ; 
                      iopzmap(Mid,'r','SD',alpha) ; 
                      title('Poles-Zeros representation (noise)') ; 
                      xlabel('Real axis') ; 
                      ylabel('Imaginary axis') ; 
                      ys = axis ; 
                      r = 's' ; 
                      if (nf==2)
                         r = [] ;
                      end 
                      text(0.8*ys(1),0.9*ys(4), ... 
                           [int2str(nf-1) ' pole' r]) ; 
                      r = 's' ; 
                      if (nc==2)
                         r = [] ;
                      end 
                      text(0.8*ys(2),0.9*ys(4), ... 
                           [int2str(nc-1) ' zero' r]) ; 
                      set(FIG,'DefaultTextHorizontalAlignment','left') ; 
                      text(1.1*ys(2),ys(3),'<Press a key>') ;
                   %pause ;
                end 
                FIG = FIG-2 ; 
             end  % [if (pf)]
          end  % [if ((nf>1) | (nb>1)) ]
        end %[for nd=1:Nd]
    end  % [for nc=1:Nc]
  end  % [for nb=1:Nb]
end  % [for nf=1:Nf]
if (~pf)
   war_err([blanks(6) '... Done.']) ; 
end  
% 
% Proposing the optimal structure
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[nb,nc,nd,nf] = GAIC_R4(Lambda,N) ; 
optidx = [optidx ; [nb,nc,nd,nf]] ; 
war_err('* Proposed optimal indices:') ; 
disp(['<F-test on prediction error>: ' ... 
      '[nb,nc,nd,nf] = [' sprintf(' %d',optidx(1,:)-1) ']']) ; 
M{optidx(1,1),optidx(1,2),optidx(1,3),optidx(1,4)}
disp(['<F-test on fitness (identification data)>: ' ... 
      '[nb,nc,nd,nf] = [' sprintf(' %d',optidx(2,:)-1) ']']) ; 
M{optidx(2,1),optidx(2,2),optidx(2,3),optidx(2,4)}
disp(['<F-test on fitness (validation data)>: ' ... 
      '[nb,nc,nd,nf] = [' sprintf(' %d',optidx(3,:)-1) ']']) ; 
M{optidx(3,1),optidx(3,2),optidx(3,3),optidx(3,4)}
disp(['<GAIC-Rissanen criterion>: ' ... 
      '[nb,nc,nd,nf] = [' sprintf(' %d',optidx(4,:)-1) ']']) ; 
M{optidx(4,1),optidx(4,2),optidx(4,3),optidx(4,4)}
% 
% Selecting the optimal structure
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
disp(' ') ;
nf = input('# Insert optimal indices [nb,nc,nd,nf]: ') ; 
nf = abs(round(nf(1:4))) ; 
nd = min(Nd,nf(3))+1 ;
nc = min(Nc,nf(2))+1 ; 
nb = min(Nb,nf(1))+1 ; 
nf = min(Nf,nf(4))+1 ; 
Mid = M{nb,nc,nd,nf} ; 
Yid = Yid{nb,nc,nd,nf} ; 
Yva = Yva{nb,nc,nd,nf} ; 
PEid = PEid{nb,nc,nd,nf}.y ; 
PEva = PEva{nb,nc,nd,nf}.y ; 
Eid = Eid(nb,nc,nd,nf) ; 
Eva = Eva(nb,nc,nd,nf) ; 
Viid = Viid(nb,nc,nd,nf) ; 
Viva = Viva(nb,nc,nd,nf) ; 
war_err('o Optimum model: ') ; 
Mid
war_err([blanks(25) '<Press a key>']) ; 
pause
% 
% Plotting model performances
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~
figure(FIG),clf
   fig_look(FIG,1.5) ; 
   subplot(321)
      plot(1:N,Did.y,'-b',1:N,Yid,'-r') ; 
      title('Identification data') ; 
      ylabel('Outputs') ; 
      ys = [min(min(Did.y),min(Yid)) ... 
            max(max(Did.y),max(Yid))] ; 
      dy = ys(2)-ys(1) ; 
      axis([0 N+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
      text(1.22*N,ys(2)+0.45*dy, ... 
            ['nb = ' int2str(nb-1) ... 
            ' | nc = ' int2str(nc-1) ... 
            ' | nd = ' int2str(nd-1)...
            ' | nf = ' int2str(nf-1)] ) ; 
      text(N/2,ys(2)+0.05*dy, ... 
           ['Fitness E_N = ' sprintf('%g',Eid) ' %']) ;
   subplot(322)
      plot(1:N,Dva.y,'-b',1:N,Yva,'-r') ; 
      title('Validation data') ; 
      ylabel('Outputs') ; 
      ys = [min(min(Dva.y),min(Yva)) ... 
            max(max(Dva.y),max(Yva))] ; 
      dy = ys(2)-ys(1) ; 
      axis([0 N+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
      text(N/2,ys(2)+0.05*dy, ... 
           ['Fitness E_N = ' sprintf('%g',Eva) ' %']) ;
      set(FIG,'DefaultTextHorizontalAlignment','left') ; 
      legend('y','ym') ; 
      set(FIG,'DefaultTextHorizontalAlignment','center') ; 
   subplot(323)
      plot(1:N,PEid,'-m') ; 
      ylabel('Prediction error') ; 
      ys = [min(PEid) max(PEid)] ; 
      dy = ys(2)-ys(1) ; 
      axis([0 N+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
      text(N/2,ys(2)+0.07*dy, ... 
           ['\lambda^2 = ' sprintf('%g',std(PEid,1)^2)]) ;
   subplot(324)
      plot(1:N,PEva,'-m') ; 
      ylabel('Prediction error') ; 
      ys = [min(PEva) max(PEva)] ; 
      dy = ys(2)-ys(1) ; 
      axis([0 N+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
      text(N/2,ys(2)+0.07*dy, ... 
           ['\lambda^2 = ' sprintf('%g',std(PEva,1)^2)]) ; 
   subplot(325)
      set(FIG,'DefaultLineLineWidth',0.5) ; 
      set(FIG,'DefaultLineMarkerSize',2) ; 
      [r,K] = xcov(PEid,'unbiased') ; 
      r = r(K>=0) ; 
      K = ceil(length(r)/2) ; 
      r = r(1:K) ; 
      stem(1:K,r,'-g','filled') ; 
      xlabel('Normalized time') ; 
      ylabel('Auto-covariance') ; 
      ys = [min(r) max(r)] ; 
      dy = ys(2)-ys(1) ; 
      axis([0 K+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
      text(K/2,ys(2)+0.05*dy, ... 
           ['Validation index = ' num2str(Viid)]) ; 
   subplot(326)
      [r,K] = xcov(PEva,'unbiased') ; 
      r = r(K>=0) ; 
      K = ceil(length(r)/2) ; 
      r = r(1:K) ; 
      stem(1:K,r,'-g','filled') ; 
      xlabel('Normalized time') ; 
      ylabel('Auto-covariance') ; 
      ys = [min(r) max(r)] ; 
      dy = ys(2)-ys(1) ; 
      axis([0 K+1 ys(1)-0.05*dy ys(2)+0.2*dy]) ;
      text(K/2,ys(2)+0.05*dy, ... 
           ['Validation index = ' num2str(Viva)]) ; 
      set(FIG,'DefaultTextHorizontalAlignment','right') ; 
      text(1.3*K,ys(1)-0.4*dy,'<Press a key>') ;
FIG = FIG+1 ; 
pause ;
figure(FIG),clf
   fig_look(FIG,2) ; 
   iopzmap(Mid,'SD',alpha) ; 
   title('Poles-Zeros representation (system)') ; 
   xlabel('Real axis') ; 
   ylabel('Imaginary axis') ; 
   ys = axis ; 
   r = 's' ; 
   if (nf==2)
      r = [] ;
   end 
   text(0.8*ys(1),0.9*ys(4), ... 
        [int2str(nf-1) ' pole' r]) ; 
   r = 's' ; 
   if (nb==2)
      r = [] ;
   end  
   text(0.8*ys(2),0.9*ys(4), ... 
        [int2str(nb-1) ' zero' r]) ; 
FIG = FIG+1 ; 
if ((nd>1) || (nc>1))
   pause ;
   P = Mid ; 
   P.b = P.c ; 
   P.a = P.d;
   P.f = 1;
   P.nk = 0 ; 
   figure(FIG),clf ;
      fig_look(FIG,2) ; 
      iopzmap(P,'r','SD',alpha) ; 
      title('Poles-Zeros representation (noise)') ; 
      xlabel('Real axis') ; 
      ylabel('Imaginary axis') ; 
      ys = axis ; 
      r = 's' ; 
      if (nd==2)
         r = [] ;
      end 
      text(0.8*ys(1),0.9*ys(4), ... 
           [int2str(nd-1) ' pole' r]) ; 
      r = 's' ; 
      if (nc==2)
         r = [] ;
      end 
      text(0.8*ys(2),0.9*ys(4), ... 
           [int2str(nc-1) ' zero' r]) ; 
      set(FIG,'DefaultTextHorizontalAlignment','left') ; 
                   text(1.1*ys(2),ys(3),'<Press a key>') ;
   FIG = FIG+1 ; 
   pause ;
end  
%
% END
%